version: "3"
services:
  zookeeper:
    image: zookeeper:3.4
    container_name: zook5
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      app_net:
        ipv4_address: 172.16.121.2
  mesos-master:
    image: mesosphere/mesos-master:1.6.2
    container_name: masterk5
    privileged: true
    hostname: localhost
    ports:
      - "5050:5050"
    networks:
      app_net:
        ipv4_address: 172.16.121.3
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_CLUSTER=docker-compose
      - MESOS_REGISTRY=replicated_log # default is in_memory for some reason
      - MESOS_HOSTNAME=localhost
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - LIBPROCESS_IP=172.16.121.3
    extra_hosts:
      - host.docker.internal:host-gateway
  mesos-slave:
    image: mesosphere/mesos-slave:1.6.2
    container_name: slavek5
    privileged: true
    hostname: localhost
    ports:
      - "5051:5051"
    networks:
      app_net:
        ipv4_address: 172.16.121.4
    links:
      - zookeeper:zookeeper
      - mesos-master:master.mesos
    depends_on:
      - zookeeper
      - mesos-master
    pid: host
    environment:
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_CONTAINERIZERS=docker
      - MESOS_PORT=5051
      - MESOS_RESOURCES=ports(*):[11000-11999]
      - MESOS_HOSTNAME=host.docker.internal
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_DOCKER_STORE_DIR=/var/lib/mesos/store
      - MESOS_IMAGE_PROVIDERS=docker
      - MESOS_ISOLATION=cgroups/cpu,cgroups/mem,docker/runtime,filesystem/linux
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - MESOS_LOG_DIR=/var/log/mesos
      - LIBPROCESS_IP=172.16.121.4
    volumes:
      - /var/lib/mesos:/var/lib/mesos:shared
      - /cgroup:/cgroup
      - /sys:/sys
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
  marathon:
    image: mesosphere/marathon:v1.11.26
    container_name: marathonk5
    hostname: localhost
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.16.121.5
    links:
      - zookeeper
      - mesos-master
    depends_on:
      - zookeeper
      - mesos-master
      - mesos-slave
    environment:
      - MARATHON_ZK=zk://zookeeper:2181/marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - LIBPROCESS_IP=172.16.121.5
    extra_hosts:
      - host.docker.internal:host-gateway
  marathon-lb:
    image: mesosphere/marathon-lb:latest
    container_name: marathon-lbk5
    hostname: localhost
    ports:
      - "9090:9090"
      - "9091:9091"
      - "80:80"
      - "12192:12192"
      - "443:443"
    networks:
      app_net:
        ipv4_address: 172.16.121.6
    links:
      - marathon
    depends_on:
      - marathon
    command: [ poll, --group, local, --marathon, http://marathon:8080, --haproxy-map, --group-https-by-vhost ]
    environment:
      - PORTS=9090
      - LIBPROCESS_IP=172.16.121.6
    extra_hosts:
      - host.docker.internal:host-gateway
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.121.0/24
