version: "3.9"
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      app_net:
        ipv4_address: 172.16.121.2
    #    volumes: # TODO Unable to restart with mounted volumes
    #      - zookeeper-volumes:/datalog
    #      - zookeeper-volumes:/logs
    #      - zookeeper-volumes:/data
    healthcheck:
      test: "echo stat | nc localhost $$ZOOKEEPER_CLIENT_PORT" # TODO ?

  mesos-master:
    container_name: master
    image: mesosphere/mesos-master:1.6.2
    privileged: true
    hostname: localhost
    ports:
      - "5050:5050"
    networks:
      app_net:
        ipv4_address: 172.16.121.3
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_CLUSTER=main-cluster
      - MESOS_ROLES=development,production
      - MESOS_REGISTRY=in_memory
      - MESOS_HOSTNAME=localhost
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - LIBPROCESS_IP=172.16.121.3
      - MESOS_LOGGING_LEVEL=INFO
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: "curl -f http://localhost:5050/health || exit 1" # TODO ?

  mesos-slave-0:
    container_name: slave-0
    image: mesosphere/mesos-slave:1.6.2
    privileged: true
    pid: host
    hostname: localhost
    ports:
      - "5051:5051"
    networks:
      app_net:
        ipv4_address: 172.16.121.7
    links:
      - zookeeper:zookeeper
      - mesos-master:master.mesos
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      - MESOS_HOSTNAME=host.docker.internal
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_RESOURCES=ports(*):[8001-8499];ephemeral_ports:[32768-57344];cpu(*):4;mem(*):8192;disk(*):32768
      - MESOS_EPHEMERAL_PORTS_PER_CONTEINER=1024
      - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem,network/port_mapping
      - MESOS_PORT=5051
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - LIBPROCESS_IP=172.16.121.7
      - MESOS_LAUNCHER=posix
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_LOGGING_LEVEL=INFO
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup
      - mesos-slave-0-volumes:/usr/local/bin/docker:/usr/local/bin/docker

  mesos-slave-1:
    container_name: slave-1
    image: mesosphere/mesos-slave:1.6.2
    privileged: true
    pid: host
    hostname: localhost
    ports:
      - "5052:5052"
    networks:
      app_net:
        ipv4_address: 172.16.121.8
    links:
      - zookeeper:zookeeper
      - mesos-master:master.mesos
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      - MESOS_HOSTNAME=host.docker.internal
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_RESOURCES=ports(*):[8500-8999]
      - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
      - MESOS_PORT=5052
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - LIBPROCESS_IP=172.16.121.8
      - MESOS_LAUNCHER=posix
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_LOGGING_LEVEL=INFO
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup
      - mesos-slave-1-volumes:/usr/local/bin/docker:/usr/local/bin/docker

  mesos-slave-2:
    container_name: slave-2
    image: mesosphere/mesos-slave:1.6.2
    privileged: true
    pid: host
    hostname: localhost
    ports:
      - "5053:5053"
    networks:
      app_net:
        ipv4_address: 172.16.121.9
    links:
      - zookeeper:zookeeper
      - mesos-master:master.mesos
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      - MESOS_HOSTNAME=host.docker.internal
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_RESOURCES=ports(*):[11000-11999]
      - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
      - MESOS_PORT=5053
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - LIBPROCESS_IP=172.16.121.9
      - MESOS_LAUNCHER=posix
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_LOGGING_LEVEL=INFO
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup
      - mesos-slave-2-volumes:/usr/local/bin/docker:/usr/local/bin/docker

  marathon:
    container_name: marathon
    image: mesosphere/marathon:latest
    entrypoint:
      - ./bin/start
      - --disable_ha
    hostname: localhost
    ports:
      - "5000:8080"
    networks:
      app_net:
        ipv4_address: 172.16.121.4
    links:
      - zookeeper
      - mesos-master
    depends_on:
      - zookeeper
      - mesos-master
      - mesos-slave-0
      - mesos-slave-1
      - mesos-slave-2
    environment:
      - MARATHON_ZK=zk://zookeeper:2181/marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - LIBPROCESS_IP=172.16.121.4
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MARATHON_LOGGING_LEVEL=INFO
    extra_hosts:
      - host.docker.internal:host-gateway

  marathon-lb:
    image: mesosphere/marathon-lb:latest
    container_name: marathon-lb
    hostname: localhost
    ports:
      - "80:80"
      - "443:443"
      - "9092:9090"
      - "9091:9091"
      - "12192:12192"
    networks:
      app_net:
        ipv4_address: 172.16.121.5
    links:
      - marathon
    depends_on:
      - marathon
    command: [ poll, --group, local, --marathon, http://marathon:8080, --haproxy-map, --group-https-by-vhost ]
    environment:
      - PORTS=9092
      - LIBPROCESS_IP=172.16.121.5
    extra_hosts:
      - host.docker.internal:host-gateway

  chronos:
    image: mesosphere/chronos:latest
    container_name: chronos
    hostname: localhost
    ports:
      - "4400:4400"
    networks:
      app_net:
        ipv4_address: 172.16.121.6
    depends_on:
      - zookeeper
      - mesos-master
    command: [ --zk_hosts zookeeper:2181 --master zk://zookeeper:2181/mesos ]
    environment:
      - PORT0=4400
      - PORT1=4444
      - LIBPROCESS_IP=172.16.121.6
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: "curl -f http://localhost:4400 || exit 1" # TODO ?

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.121.0/24

volumes:
  #  zookeeper-volumes: { }
  mesos-slave-0-volumes: { }
  mesos-slave-1-volumes: { }
  mesos-slave-2-volumes: { }
